import { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

type ISRProps = {
  message: string
}

const ISR: NextPage<ISRProps> = (props: ISRProps) => {
  const { message } = props
  const router = useRouter()

  if (router.isFallback) {
    return <div>Loading...</div>
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p>This page was generated by ISR at build time.</p>
        <p>{message}</p>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<ISRProps> = async () => {
  const timestamp = new Date().toLocaleString()
  const message = `getStaticProps on this page has been executed at ${timestamp}`
  console.log(message)

  return {
    props: {
      message,
    },
    revalidate: 15,
  }
}

export default ISR
