import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

type SSGProps = {
  message: string
}

const SSGPage: NextPage<SSGProps> = (props) => {
  const { message } = props

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p>This page was generated by SSG at build time.</p>
        <p>{message}</p>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<SSGProps> = async () => {
  const timestamp = new Date().toLocaleString()
  const message = `getStaticProps on this page has been executed at ${timestamp}`

  console.log(message)
  return {
    props: {
      message,
    },
  }
}

export default SSGPage
